version: '3.8'

services:
  test:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: test
    volumes:
      - coverage:/coverage

  build:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: export
    volumes:
      - ../dist:/output

volumes:
  coverage:
